### ISSUE TITLE
Home link in navbar always highlighted

### ISSUE THREAD

**Issue by jere-mie** [UWindsorCSS/wiki#103]
#### Expected Behaviour
The home link should only be highlighted when on the homepage

#### Actual Behaviour
No matter what page you're on, the link is highlighted in the navbar

#### Steps to Reproduce
Navigate to any page other than the homepage and look at the navbar
-

![image](https://user-images.githubusercontent.com/47261508/184523266-692fe1f7-ce56-487d-9b2e-2bd30c87620e.png)

**Comment by prairir** [comment]
I believe that this is happening because the nav bar uses react router. React router matches based on regex and home is at `/`.

**Comment by jere-mie** [comment]
that's kinda dumb ngl but makes sense
