### ISSUE TITLE
Switch Light and Dark mode bug

### ISSUE THREAD

**Issue by hassanuahmad** [UWindsorCSS/wiki#107]
#### Expected Behaviour

The icon should turn to a different color so its visible

#### Actual Behaviour

The icon is white and when you hover over, that's also white

#### Steps to Reproduce

Hover over the icon

![Screen Shot 2022-08-14 at 4 10 37 PM](https://user-images.githubusercontent.com/72142523/184553241-adfaad88-9468-49d7-93b3-c6470ed31ddb.png)

-

**Comment by prairir** [comment]
What browser are you using? I don't have this issue with firefox or any other chromium based browser

**Comment by hassanuahmad** [comment]
Safari, I guess its a safari issue then

**Comment by hassanuahmad** [comment]
I just tried it on brave, I am having the same issue

**Comment by prairir** [comment]
Safari has a large amount of issues. Safari is known as the new IE of webdev. 

also its weird that brave is having the same issue

**Comment by prairir** [comment]
I'm sorry, I have been having that issue. I was just misunderstanding what the actual issue was. I am experiencing it too.
