### ISSUE TITLE
Add newsletters

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#113]
#### Describe Problem
We have a newsletter section with no newsletters
#### Suggest Solution
upload the newsletters in the newsletters section
#### Additional Details
it should be in text format. currently its in pdf format and I think thats bad for the wiki

**Comment by jere-mie** [comment]
I think rather than posting the PDF newsletters in full, we split each newsletter into their respective articles and post those as individual posts

**Comment by prairir** [comment]
👀 thats a good idea. We can even post them all at the same time

**Comment by jere-mie** [comment]
I say we back date them to the month they were originally released in PDF form

**Comment by jere-mie** [comment]
did this a while back
