### ISSUE TITLE
Warn students about free textbook download websites

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#117]
#### Describe Problem
Students these days sometimes download free textbooks from websites. That is illegal

#### Suggest Solution
We should warn students about how easy it is to download these **FREE** textbooks and that there is nothing wrong with them. 
We should warn them that it is illegal even though it is almost never enforced.

#### Additional Details
This is a warning on the U of T subreddit https://www.reddit.com/r/UofT/comments/ietrxa/not_a_link_for_free_ebooks_and_etextbooks_we_love/

**Comment by jere-mie** [comment]
this is finished
