### ISSUE TITLE
Add Uwin VPN section to first year guide

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#122]
#### Describe Problem
The first year guide does not include using the uwin VPN. This VPN is required to connect to the university network.
#### Suggest Changes
Add something explaining how to use the VPN

**Comment by prairir** [comment]
The VPN guide is finished, https://uwindsorcss.github.io/wiki/resources/guides/vpn . You would just have to link to it and explain why you need to be connected.

**Comment by Dante-Masciotra** [comment]
Has been added on first year guide
