### ISSUE TITLE
Update Important Dates

### ISSUE THREAD

**Issue by jere-mie** [UWindsorCSS/wiki#130]
#### Describe Problem
the Important Dates section is a bit out of date.

#### Suggest Solution
Remove all dates up until Fall 2022, and add more dates.  Also, add the link to the [registrars page](https://www.uwindsor.ca/registrar/events-listing) so in case we forget to update this, readers can easily find the most up to date info.

#### Additional Details
You can find all important dates here: https://www.uwindsor.ca/registrar/events-listing
**This is a great first issue, as it's pretty easy**
The file you'll need to edit is `academics/ImportantDates.md`

**Comment by Vinitvh** [comment]
Hi, I would like to work on this.

**Comment by jere-mie** [comment]
> Hi, I would like to work on this.

feel free @Vinitvh just fork and make a PR:
https://uwindsorcss.github.io/wiki/resources/guides/contributing
