### ISSUE TITLE
Expand First Year Guide

### ISSUE THREAD

**Issue by benchittle** [UWindsorCSS/wiki#149]
### Which Article Needs to Be Updated?
First Year Guide

### What File Needs to be Edited?
resources/guides/first_year_guide.md

### What Needs to be Updated?
This might be better as a few separate files / guides, but here's a list of topics to cover as suggested on Discord
- A linux shell, such as BASH or ZSH
- Literally any programming language (including HTML/CSS and Scratch) (that's gonna be C because of 1400) 
- SSH
- Memory layouts of stack and heap
- Learn discrete math and C
- High school is not the same as university, you might have peaked in high school but the things you learn in university are of a higher level
- Computer Science is not only computer programming. There is math and theory involved
- Set up a local coding environment.
- Talk to people who are above first year for advice.
- Your degree doesn't get you a job, projects and experience get you a job
- Don't get intimidated if you feel like you know nothing: everyone starts somewhere

I think there are a few typos as well. More suggestions are welcome.

### Contributing Guide

Reminder to all contributors to read the [contributing guide](https://uwindsorcss.github.io/wiki/resources/guides/contributing) before making changes!

**Comment by Dante-Masciotra** [comment]
Thank you for your feedback on the first year guide. We'll review the content to avoid overlaps and ensure it strikes the right balance between support and value for all users as we don't want to clutter the guide with information.
