### ISSUE TITLE
add constitution

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#15]
#### Describe Problem
we need our constitution
#### Suggest Solution
doing it with git submodules is a good idea
#### Additional Details
adding a guide breaking down what the constitution says is a good idea too

**Comment by bachittle** [comment]
for reference here is where the constitution is located: https://github.com/UWindsorCSS/Documents/blob/master/constitution.md

**Comment by bachittle** [comment]
this would be located under CSS, correct?

**Comment by prairir** [comment]
@pekcus this issue

**Comment by prairir** [comment]
no more git submodule. it is best is you just move the file over to the new place and we will use it as our consitution

**Comment by prairir** [comment]
@pekcus forgot to close the issue, let me close it
