### ISSUE TITLE
Create CSS Webring

### ISSUE THREAD

**Issue by ghost** [UWindsorCSS/wiki#153]
### New Article Title

CSS Webring

### New Article Details

Allow Alumni to create a PR to add their personal website or other links to CSS.

### New Article Category

-   [ ] Course information
-   [ ] Careers
-   [ ] Academics
-   [ ] Resources
-   [x] Computer Science Society

### Contributing Guide

Reminder to all contributors to read the [contributing guide](https://uwindsorcss.github.io/wiki/resources/guides/contributing) before making changes!

**Comment by jere-mie** [comment]
I love this idea

**Comment by BorhanSaflo** [comment]
Great idea! We will certainly take this into consideration during the development of the new CSS site. Currently, we're thinking about creating a community page that includes a gallery of projects. CSS members will be able to submit their projects/pages and we can review and assign appropriate tags to them.
