### ISSUE TITLE
Create a site map

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#16]
#### Describe Problem
we need a sitemap/navigation guide on how to navigate the wiki
#### Suggest Solution
create a site map and explain in detail what every section is and how to find answers for basic questions
#### Additional Details
it may also be a good idea to put an FAQ in a related section

**Comment by prairir** [comment]
This would be good to do this last

**Comment by hassanuahmad** [comment]
Should we be good with closing this issue or do we want to complete the site first then? I feel like this will be something we have to update constantly so we can add this to the PR template

**Comment by prairir** [comment]
I'm not sure about completing the site first. It would be a good idea to give a little blurb about how to navigate the site tho

**Comment by prairir** [comment]
this was completed with #141
