### ISSUE TITLE
Fix Link Casing

### ISSUE THREAD

**Issue by Dante-Masciotra** [UWindsorCSS/wiki#163]
### Issue Details

The casing of links is helloworld while others are hello_world
We should have a more consistent naming scheme

### Contributing Guide

Reminder to all contributors to read the [contributing guide](https://uwindsorcss.github.io/wiki/resources/guides/contributing) before making changes!

**Comment by kilbouri** [comment]
I personally am an advocate for `hyphenated-slugs`.

**Comment by jere-mie** [comment]
> I personally am an advocate for `hyphenated-slugs`.

I am also a huge advocate for hyphenated slugs @kilbouri

**Comment by BorhanSaflo** [comment]
I would also advocate for hyphenated slugs
