### ISSUE TITLE
Split "Recommended Software for Computer Science" section from First Year Guide

### ISSUE THREAD

**Issue by tanzimfh** [UWindsorCSS/wiki#177]
### Which Article Needs to Be Updated?

First Year Guide

### What File Needs to be Edited?

resources/guides/first-year-guide.md

### What Needs to be Updated?

The "Recommended Software for Computer Science" section has lots of helpful info for second years and beyond, but they're less likely to see it because it's contained within the First Year Guide.

Please make this a separate article and link it in the First Year Guide.

### Contributing Guide

Reminder to all contributors to read the [contributing guide](https://uwindsorcss.github.io/wiki/resources/guides/contributing) before making changes!

**Comment by Dante-Masciotra** [comment]
I like the idea of splitting it up as many people, not just first years, could use the advice. However I think there should still be a link to the new article in the first year guide as this information is still good to incoming students who want to set up a good environment

**Comment by angelohoeung** [comment]
Close pls
