### ISSUE TITLE
UWinsite Student Documentation/Guide

### ISSUE THREAD

**Issue by kilbouri** [UWindsorCSS/wiki#38]
#### Describe Problem
UWinsite Student (UWS) is very... user unfriendly to say the least. Especially for first year students who haven't seen it before. 

#### Suggest Solution
We can reduce friction by creating our own user guide to UWS, covering the basics and most common things like:
- Course management
  - Where to find course enrollment info, like appointment dates
  - How to enroll in courses
  - How to use the shopping cart
- Where to find important financial information like
  - charges due
  - opt out of drug and dental for those who want to
  - how to make payments and get refunds
  - income tax forms
- Where to find student information like
  - letter of enrollment
  - academic progress
  - student ID (because it takes a while to memorize that)
  - where to update contact information and such

#### Additional Details
Most of this stuff is really easy and located in the same place (by each section in the list, at least), so a wiki structure similar to that will probably work fairly well.

This is a **ultra-low priority item**. It is new content and is not required for a MWP

**Comment by prairir** [comment]
this was finished with #75
