### ISSUE TITLE
Add Section for UWindsor Wifi

### ISSUE THREAD

**Issue by jere-mie** [UWindsorCSS/wiki#42]
#### Describe Problem

Connecting to UWindsor wifi can be less-than easy for new students. There are also many different sources of information for students, but none of them are clear, concise, and accurate.

#### Suggest Solution

We should add a section that explains what the different wifi networks are, how to connect to them, some troubleshooting steps, and where to reach out if they have any other issues.

#### Additional Details

Here are a few different links with info that you may want to consult:
- https://www.uwindsor.ca/residence/wifi
- https://www.uwindsor.ca/itservices/2019-09-27/eduroam-preferred-wireless-network
- https://leddy.uwindsor.ca/library-computing/wifi
- https://www.uwindsor.ca/residence/sites/uwindsor.ca.residence/files/wifi_for_residence_students.pdf

**Comment by prairir** [comment]
To add to this, different sections for different systems would be exceptionally beneficial.

These sections could be like
- android
- linux
    - network manager
    - gnome
    - kde
- mac
- ios
- windows

I think this is specifically useful for things like eduroam which can have a very very large amount of settings

**Comment by jere-mie** [comment]
this has been completed already
