### ISSUE TITLE
Wifi instructions for linux

### ISSUE THREAD

**Issue by abdularif0705** [UWindsorCSS/wiki#47]
Can we add a section for Iphone or android? Please add issues for platforms that you dont have. for example, an issue like `Wifi instructions for linux`

_Originally posted by @prairir in https://github.com/UWindsorCSS/Wiki/pull/45#discussion_r807478567_

**Comment by prairir** [comment]
This would be for network manager frontends(nmtui, nmcli, nm-applet)

**Comment by zainaraza43** [comment]
this is the format go to town @prairir 

![image](https://user-images.githubusercontent.com/46791180/230146522-a2027493-8f05-41ac-859b-62b6fd176f15.png)

**Comment by zainaraza43** [comment]
for EDUROAM btw ^

**Comment by Dante-Masciotra** [comment]
Added change
