### ISSUE TITLE
Change PR template to use checkboxes

### ISSUE THREAD

**Issue by jere-mie** [UWindsorCSS/wiki#50]
#### Describe Problem

Currently we use a mish mash of checkboxes and free text for yes/no questions.

#### Suggest Changes

Yes or no questions should use checkboxes in the PR template instead of just a heading

#### Provide Examples
![image](https://user-images.githubusercontent.com/47261508/155833219-cd1370a8-7d46-4e6d-99e8-8826140ab66e.png)

**Comment by prairir** [comment]
This was already done
