### ISSUE TITLE
Webhook error appears on screen when I run `yarn start`

### ISSUE THREAD

**Issue by abdularif0705** [UWindsorCSS/wiki#51]
#### Expected Behaviour
http://localhost:3000/wiki/ should open up the main page after executing `yarn start`.

#### Actual Behaviour
I get an error on my screen which looks like this 

![image](https://user-images.githubusercontent.com/55670928/155861691-b2e69c75-edb4-4f07-95d4-4f861e297277.png)

To get around this issue I opened up a different file such as http://localhost:3000/wiki/resources/guides/wifi and then the error pops up but then I click [X] to exit the error tab.

![image](https://user-images.githubusercontent.com/55670928/155861623-38313757-ceae-4aae-a1ef-02819a7ab29f.png)

#### Steps to Reproduce
check out abdul-test branch and run yarn start. Once everything loads up you should the same error I'm getting

**Comment by kilbouri** [comment]
Why was this closed? Fixed? If so, how?

**Comment by abdularif0705** [comment]
# Solved the ThemeHook error that came from me running `npm install` to download Prettier

Fixed it by going back to an old commit and starting fresh from there. I used **yarn install --dev** to install the Prettier dependencies and set the **default formatter** to Prettier in VSC settings. If you are using VSC then you should install the Prettier extension.
