### ISSUE TITLE
Add parking guide

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#69]
#### Describe Problem
There isnt a parking guide
#### Suggest Solution
Add a parking guide with all the official parking spots and some unofficial spots. 
#### Additional Details
*somewhere* there is a google maps document showing all the parking spots and they are categorized. Putting that into this guide would be exceptionally helpful.

**Comment by benchittle** [comment]
Here's the Google Maps thing I think you're talking about: https://www.google.com/maps/d/viewer?mid=1-SScqZS53iq7eRSQ2jncF02icAc&hl=en_US&ll=42.30725847966636%2C-83.05670239117117&z=16
