### ISSUE TITLE
Change `offered` and `not offered` to emojis

### ISSUE THREAD

**Issue by prairir** [UWindsorCSS/wiki#77]
#### Describe Problem
courses has a huge table, reading `offered` and `not offered` can get confusing. 

#### Suggest Solution
Add an emoji at the end. Current thinking has ❌ for `not offered` and ✔️ for `offered`

My thinking is that an emoji at the end makes it easy for sighted people to see. Keeping the text makes it easier for screen readers.

Maybe change `not offered` to `non-offered` or something that is less like `offered`

**Comment by kilbouri** [comment]
I think we should remove the text all together. We can keep screen reader support with `role` and `aria-label`

https://chrislachance.com/screen-reader-friendly-emojis/

**Comment by jere-mie** [comment]
this has already been changed, so closing
