### ISSUE TITLE
Center Contents of Footer

### ISSUE THREAD

**Issue by ahmadmunim** [UWindsorCSS/wiki#81]
#### Describe Problem
The contents of the footer are somewhat left-aligned in desktop mode.

#### Suggest Solution
We can center the contents in our custom.css file. Overall, this will make the footer look nicer.

**Comment by jere-mie** [comment]
has this been fixed yet? Iirc there was a PR for this @prairir @ahmadmunim

**Comment by prairir** [comment]
IIRC @ahmadmunim was working on it but I wanted it to be worked on later as we may have changed the footer. I think its fine to work on right now

**Comment by ahmadmunim** [comment]
Yes, I was going to work on it when I found out. But since Ryan said not to work on it at the time, I left it.

**Comment by BorhanSaflo** [comment]
5113372f2f5acd28739af64a2a552f2fdc468023 solves this issue.
