### ISSUE TITLE
Add current CSS board membership info

### ISSUE THREAD

**Issue by benchittle** [UWindsorCSS/wiki#92]
#### Describe Problem
The CSS section is missing a few things (it currently only has our constitution).

#### Suggest Solution
Add a section for CSS membership containing the names, positions, and contact info for all current CSS board members, like what is found on the hub's "About" section. This could also detail how to get involved with CSS.

#### Additional Details
Hub is currently down, but usually the relevant info would be at https://css.uwindsor.ca/about

**Comment by jere-mie** [comment]
covered by https://github.com/UWindsorCSS/wiki/pull/104
